"""Extract sample data from production database for testing.

This script extracts a small, representative sample of real data from the
production toltec database to use in tests. The sample includes:
- Master entries (toltec, tcs, ics)
- A few RawObs entries spanning different obsnum/scannum values
- Related InterfaceFile and DataProd entries
- Valid and invalid interface examples

Usage:
    uv run tests/fixtures/extract_sample_data.py

Output:
    tests/fixtures/sample_data.sql - SQL INSERT statements
"""

from __future__ import annotations

from pathlib import Path
from sqlalchemy import create_engine, select, text
from sqlalchemy.orm import Session
from rich.console import Console

console = Console()


def extract_sample_data():
    """Extract sample data from toltec_db."""
    # Path to production database
    prod_db = Path(__file__).parent.parent.parent.parent / "run" / "toltecdb_last_30days.sqlite"
    
    if not prod_db.exists():
        console.print(f"[red]Production database not found: {prod_db}[/red]")
        console.print("[yellow]Run get_toltecdb.py first to download the database[/yellow]")
        return
    
    console.print(f"[green]Extracting sample data from {prod_db.name}...[/green]")
    
    engine = create_engine(f"sqlite:///{prod_db}")
    
    with Session(engine) as session:
        # Get all masters
        masters = session.execute(text("SELECT id, label FROM master ORDER BY id")).fetchall()
        console.print(f"Found {len(masters)} masters")
        
        # Get sample RawObs entries (3 different observations)
        raw_obs = session.execute(text("""
            SELECT id, master_id, obsnum, subobsnum, scannum, ut, tel_header
            FROM raw_obs
            WHERE obsnum IN (
                SELECT DISTINCT obsnum FROM raw_obs 
                ORDER BY obsnum DESC 
                LIMIT 3
            )
            ORDER BY obsnum DESC, subobsnum, scannum
            LIMIT 10
        """)).fetchall()
        console.print(f"Found {len(raw_obs)} raw_obs entries")
        
        # Get related InterfaceFile entries
        raw_obs_ids = [r[0] for r in raw_obs]
        if raw_obs_ids:
            placeholders = ','.join('?' * len(raw_obs_ids))
            interface_files = session.execute(text(f"""
                SELECT id, raw_obs_id, nw, valid, filename
                FROM interface_file
                WHERE raw_obs_id IN ({placeholders})
                ORDER BY raw_obs_id, nw
                LIMIT 50
            """), raw_obs_ids).fetchall()
            console.print(f"Found {len(interface_files)} interface_file entries")
        else:
            interface_files = []
        
        # Write SQL file
        output_file = Path(__file__).parent / "sample_data.sql"
        
        with open(output_file, 'w') as f:
            f.write("-- Sample data extracted from toltec_db for testing\n")
            f.write("-- Generated by extract_sample_data.py\n\n")
            
            # Masters
            f.write("-- Masters\n")
            for row in masters:
                f.write(f"INSERT INTO master (id, label) VALUES ({row[0]}, '{row[1]}');\n")
            f.write("\n")
            
            # RawObs
            f.write("-- RawObs entries\n")
            for row in raw_obs:
                id_, master_id, obsnum, subobsnum, scannum, ut, tel_header = row
                # Escape single quotes in JSON
                tel_header_escaped = tel_header.replace("'", "''") if tel_header else None
                ut_str = f"'{ut}'" if ut else "NULL"
                tel_str = f"'{tel_header_escaped}'" if tel_header else "NULL"
                
                f.write(f"INSERT INTO raw_obs (id, master_id, obsnum, subobsnum, scannum, ut, tel_header) ")
                f.write(f"VALUES ({id_}, {master_id}, {obsnum}, {subobsnum}, {scannum}, {ut_str}, {tel_str});\n")
            f.write("\n")
            
            # InterfaceFiles
            f.write("-- InterfaceFile entries\n")
            for row in interface_files:
                id_, raw_obs_id, nw, valid, filename = row
                filename_escaped = filename.replace("'", "''") if filename else None
                filename_str = f"'{filename_escaped}'" if filename else "NULL"
                
                f.write(f"INSERT INTO interface_file (id, raw_obs_id, nw, valid, filename) ")
                f.write(f"VALUES ({id_}, {raw_obs_id}, {nw}, {valid}, {filename_str});\n")
            f.write("\n")
        
        console.print(f"[green]✓ Sample data written to {output_file}[/green]")
        console.print(f"  - {len(masters)} masters")
        console.print(f"  - {len(raw_obs)} raw_obs entries")
        console.print(f"  - {len(interface_files)} interface_file entries")


if __name__ == "__main__":
    extract_sample_data()
